<img src="https://www.encit.unam.mx/sites/default/files/2020-10/EN%20CIENCIAS%20DE%20LA%20TIERRA1%20%281%29.png" width=200px hspace="5px" vspace="0px" style="float: left; margin-right:10px">

**Asignatura**: Herramientas Computacionales Avanzadas <br>
**Profesor**: Dr. Luis Miguel de la Cruz Salas.<br>
**Examen Práctico**: 1<br>
**Fecha**: Febrero 2024


In [ ]:
NAME = ""
COLLABORATORS = ""

---

# El atractor de Lorenz

**Objetivo general**
- Resolver numéricamente el sistema de ecuaciones de Lorenz usando el método de Euler hacia adelante.

<a name='1'></a>
## Modelo Conceptual

En 1963 Edward Lorenz definió un [sistema dinámico determinista tridimensional no lineal](https://journals.ametsoc.org/view/journals/atsc/20/2/1520-0469_1963_020_0130_dnf_2_0_co_2.xml?tab_body=pdf), el cual derivó de las ecuaciones simplificadas de rollos de convección que se producen en las ecuaciones dinámicas de la **atmósfera terrestre**. A este sistema se le conoce como **Atractor de Lorenz**,
[[Represa, Soledad. (2016). Ecuaciones de Lorenz. 10.13140/RG.2.2.18508.82563]](https://www.researchgate.net/publication/316629141_Ecuaciones_de_Lorenz).

In [ ]:
%%html
<iframe width="600" height="400" src="https://www.youtube.com/embed/XZ7Ly7dDCzo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

<a name='2'></a>
## Modelo Matemático.

El sistema definido por Lorenz presenta un comportamiento caótico y suele aparecer también en otros fenómenos físicos. Consiste de tres ecuaciones diferenciales ordinarias no lineales que se escriben como sigue:

$$
\begin{eqnarray}
\dfrac{dx}{dt} & = & \sigma(y − x), \tag{1}\\
\dfrac{dy}{dt} & = & x(\rho − z) − y, \tag{2} \\
\dfrac{dz}{dt} & = & xy − \beta z \tag{3}
\end{eqnarray}
$$

donde $\sigma$ es conocido como el número de Prandtl y $\rho$ el número de Rayleigh. Ambos son parámetros adimensionales que definen el movimiento convectivo en la atmósfera.

Usualmente $\sigma = 10$, $\beta = 8/3$, $\rho$ es variado. El sistema exhibe un comportamiento **caótico** para $\rho = 28$. Se debe cumplir que $\sigma, \beta, \rho > 0$.

En las ecuaciones anteriores, $x$ es proporcional a la intensidad del movimiento convectivo, $y$ es proporcional a la diferencia de temperaturas entre las corrientes ascendentes y descendentes y $z$ es proporcional a la desviación de la linealidad del perfil de temperaturas vertical.

Dadas las condiciones iniciales, la solución de este sistema define trayectorias en el espacio fase $xyz$ cuya forma recuerdan a una mariposa; de aquí que el atractor de Lorenz puede haber inspirado el nombre del **efecto mariposa** en la teoría del caos.

<a name='3'></a>
## Modelo Numérico

El sistema representado por las ecuaciones $(1), (2)$ y $(3)$ puede ser resuelto numéricamente aplicando el método de Euler hacia adelante que proporciona una aproximación, de orden lineal $\mathcal{O}(h_t)$, que se describe como sigue:

$$
\begin{eqnarray}
x(t_{n+1}) & = & x(t_n) + h_t * F(x, y, \sigma) \tag{4}\\
y(t_{n+1}) & = & y(t_n) + h_t * G(x, y, z, \rho) \tag{5}\\
z(t_{n+1}) & = & z(t_n) + h_t * H(x, y, z, \beta) \tag{6}
\end{eqnarray}
$$

donde:

$$
\begin{eqnarray}
F(x, y, \sigma) & = & \sigma(y − x) \tag{7}\\
G(x, y, z, \rho) & = & x(\rho − z) − y \tag{8}\\
H(x, y, z, \beta) & = & xy − \beta z \tag{9}
\end{eqnarray}
$$


Para que el método esté bien definido necesitamos condiciones iniciales:

$$
\begin{eqnarray}
x(t = 0) & = & x_0 \\
y(t = 0) & = & y_0 \\
z(t = 0) & = & z_0 \\
\end{eqnarray}
$$

La evaluación de las ecuaciones $(1)$,$(2)$ y $(3)$ genera u
Al resolver este problema obtendremos una lista de tuplas del tipo $(x_n,y_n,z_n)$ para $n=1, \dots, N_t$, que al graficarse generarán trayectorias en el espacio fase $xyz$.
En el siguiente interactivo mueva el valor de los parámetros y observe lo que sucede.

<a name='4'></a>
## Modelo Computacional

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import macti.visual
import glor
from macti.evaluation import *
quizz = Quizz('ex2_repo', 'HeCompA')

<div class="alert alert-success">

## Ejercicio 1.

<font color="Black">

Definir los siguientes dos puntos iniciales en el espacio fase $xyz$. Estos puntos iniciales serán el inicio de dos trayectorias.

$$
\begin{eqnarray}
(x_1, y_1, z_1) & = & (5.98168845,  9.14898233, 18.04053198) \\
(x_2, y_2, z_2) & = & (5.28839638,  7.82341498, 19.06587760)
\end{eqnarray}
$$

En la definición de estos puntos no omitas ningún decimal.

**Hint**.
```python
x1 = ...
y1 = ...
z1 = ...
...
```
</font>
</div>

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print("(x1, y1, z1) = ({}, {}, {})".format(x1, y1, z1))
print("(x2, y2, z2) = ({}, {}, {})".format(x2, y2, z2))

In [ ]:
quizz.eval_numeric('1', x1)
quizz.eval_numeric('2', y1)
quizz.eval_numeric('3', z1)
quizz.eval_numeric('4', x2)
quizz.eval_numeric('5', y2)
quizz.eval_numeric('6', z2)

<div class="alert alert-success">

## Ejercicio 2.

<font color="Black">
    
Definir el número total de pasos de tiempo $Nt$. En este ejemplo usaremos $5000$ pasos de tiempo. 

**Hint**.
```python
Nt = ...
```
</font>
</div>

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print("Nt = {}".format(Nt))

In [ ]:
quizz.eval_numeric('7', Nt)

<div class="alert alert-success">

## Ejercicio 3.

<font color="Black">
    
Definir los arreglos `track_1` y `track_2` para almacenar las coordenadas de cada punto de las dos trayectorias. Ambos arreglos serán de dimensión `(3, Nt)` y tendrán la siguiente forma:

```
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
````
<br>

**Hint**.
```python
track_1 = np.zeros(...)
...
```

</font>
</div>

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print("track_1 = \n{}".format(track_1))
print("\ntrack_2 = \n{}".format(track_2))

In [ ]:
quizz.eval_numeric('8', track_1.shape)
quizz.eval_numeric('9', track_2.shape)

<div class="alert alert-success">

## Ejercicio 4.

<font color="Black">
    
Inicializa los arreglos `track_1` y `track_2` con los puntos iniciales de cada trayectoria. Por ejemplo, para el arreglo `track_1` deberás obtener un resultado como el siguiente:

```
[[ 5.98168845  0.          0.         ...  0.          0.
   0.        ]
 [ 9.14898233  0.          0.         ...  0.          0.
   0.        ]
 [18.04053198  0.          0.         ...  0.          0.
   0.        ]]
```

**Hint**.
```python
track_1[0,0] = ...
track_1[1,0] = ...
track_1[2,0] = ...
...
```
</font>
</div>

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print("track_1 = \n{}".format(track_1))
print("\ntrack_2 = \n{}".format(track_2))

In [ ]:
quizz.eval_numeric('10', track_1[:,0])
quizz.eval_numeric('11', track_2[:,0])

<div class="alert alert-success">

## Ejercicio 5.

<font color="Black">
    
Definir las siguientes funciones de Python para evaluar las funciones matemáticas $F$, $G$ y $H$, (ecuaciones $7$, $8$ y $9$) de las ecuaciones de Lorenz:

```python
def F(x, y, 𝜎):
    return ...

def G(x, y, z, 𝜌):
    return ...

def H(x, y, z, 𝛽):
    return ...
```
</font>
</div>

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

<div class="alert alert-success">

## Ejercicio 6.

<font color="Black">
    
Implementar el método de Euler hacia adelante para resolver las ecuaciones de Lorenz. Recuerda que:

$$
\begin{eqnarray}
x(t_{n+1}) & = & x(t_n) + h_t * F(x, y, \sigma) \tag{4}\\
y(t_{n+1}) & = & y(t_n) + h_t * G(x, y, z, \rho) \tag{5}\\
z(t_{n+1}) & = & z(t_n) + h_t * H(x, y, z, \beta) \tag{6}
\end{eqnarray}
$$

Almacena las coordenadas ($x(t_{n+1})$, $y(t_{n+1})$, $z(t_{n+1})$) en los arreglos `track_*`.

Grafica las trayectorias en 3D en el espacio fase $xyz$ y en 2D en el espacio $xz$. Las graficas deberán ser similares a las siguientes:

<img src="Lorenz.png" width=500px>

**Hint**.

* Define $\sigma = 10.0$.
* Define $\beta = 8 / 3$.
* Define con un valor $\rho$ entre los siguientes: $27.5$ $28.0$ $28.5$ y $29.0$.
* Elige un valor para $dt$ entre los siguientes: $0.02$, $0.01$, $0.005$, $0.001$.
* Debes realizar un ciclo `for` para recorrer el tiempo $t$ en todo el rango $(0, Nt)$.
* Dentro del ciclo `for`, para cada una de las dos trayectorias, implementa las ecuaciones $(4)$, $(5)$ y $(6)$.
* En este caso tenemos que, para la trayectoria 1:
    * $x(t_n) \equiv$ track_1[0,t]
    * $y(t_n) \equiv$ track_1[1,t]
    * $z(t_n) \equiv$ track_1[2,t]
      
 Lo mismo para la trayectoria 2.
</font>
</div>

In [ ]:
# Debes definir lo siguiente:
#𝜎 = ... 
#𝛽 = ... 
#𝜌 = ... 
#dt = ...

# Y luego un ciclo for:
# for t in ...:
#    implementar el algoritmo de Euler hacia adelante

# YOUR CODE HERE
raise NotImplementedError()

print('{:>20s} = {:5.2f}'.format('Número de Prandtl 𝜎', 𝜎))
print('{:>20s} = {:5.2f}'.format('Número de Rayleigh 𝜌', 𝜌)) 
print('{:>20s} = {:>5.2f}'.format('Valor de 𝛽', 𝛽))
print('{:>20s} = {:>6.3f}'.format('dt', dt))
print("track_1 = \n{}".format(track_1))
print("\ntrack_2 = \n{}".format(track_2))

In [ ]:
# Graficación de las trayectorias en el espacio fase
fig = plt.figure(figsize=(10,5))
glor.plot_trayectorias(fig, track_1, track_2)
plt.tight_layout()
plt.show()

In [ ]:
quizz.eval_numeric('12', 𝜌)
quizz.eval_numeric('13', dt)
quizz.eval_numeric('14', track_1)
quizz.eval_numeric('15', track_2)